[2024-05-29T00:31:29.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T00:31:29.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T07:30:00+00:00 [queued]>
[2024-05-29T00:31:29.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T07:30:00+00:00 [queued]>
[2024-05-29T00:31:29.401+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T00:31:29.442+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 07:30:00+00:00
[2024-05-29T00:31:29.463+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=299) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T00:31:29.467+0000] {standard_task_runner.py:63} INFO - Started process 316 to run task
[2024-05-29T00:31:29.469+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T07:30:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmplrz_x9t6']
[2024-05-29T00:31:29.473+0000] {standard_task_runner.py:91} INFO - Job 160: Subtask criar_pasta
[2024-05-29T00:31:29.620+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T07:30:00+00:00 [running]> on host 0473b835f7f4
[2024-05-29T00:31:29.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T07:30:00+00:00'
[2024-05-29T00:31:29.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T00:31:29.807+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T00:31:29.808+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-29T00:31:29.828+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T07:30:00+00:00, execution_date=20240517T073000, start_date=20240529T003129, end_date=20240529T003129
[2024-05-29T00:31:29.861+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 160 for task criar_pasta (name 'Path' is not defined; 316)
[2024-05-29T00:31:29.900+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T00:31:29.934+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T00:31:29.940+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:42:59.718+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:42:59.788+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T07:30:00+00:00 [queued]>
[2024-05-29T01:42:59.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T07:30:00+00:00 [queued]>
[2024-05-29T01:42:59.827+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:42:59.885+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 07:30:00+00:00
[2024-05-29T01:42:59.918+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=345) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:42:59.923+0000] {standard_task_runner.py:63} INFO - Started process 369 to run task
[2024-05-29T01:42:59.923+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T07:30:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpenjxvm9t']
[2024-05-29T01:42:59.930+0000] {standard_task_runner.py:91} INFO - Job 238: Subtask criar_pasta
[2024-05-29T01:43:00.115+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T07:30:00+00:00 [running]> on host 6665b0710315
[2024-05-29T01:43:00.360+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T07:30:00+00:00'
[2024-05-29T01:43:00.366+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:43:00.375+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:43:00.379+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:43:00.402+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T07:30:00+00:00, execution_date=20240517T073000, start_date=20240529T014259, end_date=20240529T014300
[2024-05-29T01:43:00.490+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:43:00.549+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:43:00.552+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
