[2024-05-25T19:05:09.417+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:05:09.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T00:10:00+00:00 [queued]>
[2024-05-25T19:05:09.457+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T00:10:00+00:00 [queued]>
[2024-05-25T19:05:09.458+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:05:09.477+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 00:10:00+00:00
[2024-05-25T19:05:09.486+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:05:09.487+0000] {standard_task_runner.py:63} INFO - Started process 183 to run task
[2024-05-25T19:05:09.488+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T00:10:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpfzlslvq0']
[2024-05-25T19:05:09.490+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask criar_pasta
[2024-05-25T19:05:09.545+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T00:10:00+00:00 [running]> on host 0473b835f7f4
[2024-05-25T19:05:09.655+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:10:00+00:00'
[2024-05-25T19:05:09.657+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:05:09.658+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:05:09.659+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-25T19:05:09.673+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T00:10:00+00:00, execution_date=20240517T001000, start_date=20240525T190509, end_date=20240525T190509
[2024-05-25T19:05:09.701+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task criar_pasta (name 'Path' is not defined; 183)
[2024-05-25T19:05:09.751+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:05:09.783+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:05:09.789+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:35:33.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:35:33.385+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T00:10:00+00:00 [queued]>
[2024-05-29T01:35:33.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T00:10:00+00:00 [queued]>
[2024-05-29T01:35:33.409+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:35:33.466+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 00:10:00+00:00
[2024-05-29T01:35:33.493+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:35:33.500+0000] {standard_task_runner.py:63} INFO - Started process 290 to run task
[2024-05-29T01:35:33.503+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T00:10:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpy3asmsx0']
[2024-05-29T01:35:33.512+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask criar_pasta
[2024-05-29T01:35:33.786+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T00:10:00+00:00 [running]> on host dd333ca35f8c
[2024-05-29T01:35:34.111+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:10:00+00:00'
[2024-05-29T01:35:34.130+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:35:34.138+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:35:34.143+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:35:34.181+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T00:10:00+00:00, execution_date=20240517T001000, start_date=20240529T013533, end_date=20240529T013534
[2024-05-29T01:35:34.255+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:35:34.322+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:35:34.330+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
