[2024-05-29T00:46:33.792+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T00:46:33.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-20T19:05:00+00:00 [queued]>
[2024-05-29T00:46:33.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-20T19:05:00+00:00 [queued]>
[2024-05-29T00:46:33.845+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T00:46:33.874+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair_dados> on 2024-05-20 19:05:00+00:00
[2024-05-29T00:46:33.885+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5029) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T00:46:33.888+0000] {standard_task_runner.py:63} INFO - Started process 5034 to run task
[2024-05-29T00:46:33.888+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'extrair_dados', 'scheduled__2024-05-20T19:05:00+00:00', '--job-id', '1674', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpfden28yp']
[2024-05-29T00:46:33.890+0000] {standard_task_runner.py:91} INFO - Job 1674: Subtask extrair_dados
[2024-05-29T00:46:33.976+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-20T19:05:00+00:00 [running]> on host 0473b835f7f4
[2024-05-29T00:46:34.128+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='extrair_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T19:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T19:05:00+00:00'
[2024-05-29T00:46:34.131+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T00:46:34.133+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T00:46:34.135+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/etl/extract.py", line 7, in extrair_dados
    data_interval_end_plus_7 = data_interval_end.add(days=7).strftime("%Y-%m-%d")
                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'add'
[2024-05-29T00:46:34.151+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=extrair_dados, run_id=scheduled__2024-05-20T19:05:00+00:00, execution_date=20240520T190500, start_date=20240529T004633, end_date=20240529T004634
[2024-05-29T00:46:34.170+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1674 for task extrair_dados ('str' object has no attribute 'add'; 5034)
[2024-05-29T00:46:34.192+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T00:46:34.219+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T00:46:34.222+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
