[2024-05-25T19:05:28.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:05:28.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T02:45:00+00:00 [queued]>
[2024-05-25T19:05:28.076+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T02:45:00+00:00 [queued]>
[2024-05-25T19:05:28.077+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:05:28.092+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 02:45:00+00:00
[2024-05-25T19:05:28.100+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=265) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:05:28.102+0000] {standard_task_runner.py:63} INFO - Started process 284 to run task
[2024-05-25T19:05:28.102+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T02:45:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpllbr7t4e']
[2024-05-25T19:05:28.103+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask criar_pasta
[2024-05-25T19:05:28.156+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T02:45:00+00:00 [running]> on host 0473b835f7f4
[2024-05-25T19:05:28.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T02:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T02:45:00+00:00'
[2024-05-25T19:05:28.244+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:05:28.244+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:05:28.245+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-25T19:05:28.253+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T02:45:00+00:00, execution_date=20240517T024500, start_date=20240525T190528, end_date=20240525T190528
[2024-05-25T19:05:28.265+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task criar_pasta (name 'Path' is not defined; 284)
[2024-05-25T19:05:28.283+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:05:28.303+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:05:28.307+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:36:30.130+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:36:30.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T02:45:00+00:00 [queued]>
[2024-05-29T01:36:30.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T02:45:00+00:00 [queued]>
[2024-05-29T01:36:30.258+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:36:30.301+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 02:45:00+00:00
[2024-05-29T01:36:30.327+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=474) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:36:30.333+0000] {standard_task_runner.py:63} INFO - Started process 491 to run task
[2024-05-29T01:36:30.344+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T02:45:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmp8aglahl9']
[2024-05-29T01:36:30.353+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask criar_pasta
[2024-05-29T01:36:30.612+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T02:45:00+00:00 [running]> on host dd333ca35f8c
[2024-05-29T01:36:31.034+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T02:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T02:45:00+00:00'
[2024-05-29T01:36:31.042+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:36:31.045+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:36:31.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:36:31.091+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T02:45:00+00:00, execution_date=20240517T024500, start_date=20240529T013630, end_date=20240529T013631
[2024-05-29T01:36:31.195+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:36:31.271+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:36:31.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
