[2024-05-25T19:04:47.713+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:04:47.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-16T21:35:00+00:00 [queued]>
[2024-05-25T19:04:47.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-16T21:35:00+00:00 [queued]>
[2024-05-25T19:04:47.770+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:04:47.908+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-16 21:35:00+00:00
[2024-05-25T19:04:47.930+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:04:47.935+0000] {standard_task_runner.py:63} INFO - Started process 100 to run task
[2024-05-25T19:04:47.937+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-16T21:35:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpliirr_cv']
[2024-05-25T19:04:47.940+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask criar_pasta
[2024-05-25T19:04:48.153+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-16T21:35:00+00:00 [running]> on host 0473b835f7f4
[2024-05-25T19:04:48.631+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T21:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T21:35:00+00:00'
[2024-05-25T19:04:48.634+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:04:48.640+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:04:48.642+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-25T19:04:48.680+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-16T21:35:00+00:00, execution_date=20240516T213500, start_date=20240525T190447, end_date=20240525T190448
[2024-05-25T19:04:48.749+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task criar_pasta (name 'Path' is not defined; 100)
[2024-05-25T19:04:48.826+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:04:48.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:34:40.831+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:34:40.913+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-16T21:35:00+00:00 [queued]>
[2024-05-29T01:34:40.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-16T21:35:00+00:00 [queued]>
[2024-05-29T01:34:40.945+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:34:41.008+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-16 21:35:00+00:00
[2024-05-29T01:34:41.029+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:34:41.040+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-05-29T01:34:41.046+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-16T21:35:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmp8rh3idtx']
[2024-05-29T01:34:41.050+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask criar_pasta
[2024-05-29T01:34:41.238+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-16T21:35:00+00:00 [running]> on host dd333ca35f8c
[2024-05-29T01:34:41.479+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T21:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T21:35:00+00:00'
[2024-05-29T01:34:41.485+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:34:41.493+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:34:41.494+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:34:41.545+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-16T21:35:00+00:00, execution_date=20240516T213500, start_date=20240529T013440, end_date=20240529T013441
[2024-05-29T01:34:41.648+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:34:41.715+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:34:41.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
