[2024-05-29T00:48:53.901+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T00:48:53.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-21T07:15:00+00:00 [queued]>
[2024-05-29T00:48:53.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-21T07:15:00+00:00 [queued]>
[2024-05-29T00:48:53.994+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T00:48:54.061+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair_dados> on 2024-05-21 07:15:00+00:00
[2024-05-29T00:48:54.083+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5950) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T00:48:54.088+0000] {standard_task_runner.py:63} INFO - Started process 5982 to run task
[2024-05-29T00:48:54.090+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'extrair_dados', 'scheduled__2024-05-21T07:15:00+00:00', '--job-id', '1977', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpl57y1tbv']
[2024-05-29T00:48:54.097+0000] {standard_task_runner.py:91} INFO - Job 1977: Subtask extrair_dados
[2024-05-29T00:48:54.291+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-21T07:15:00+00:00 [running]> on host 0473b835f7f4
[2024-05-29T00:48:54.466+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='extrair_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T07:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T07:15:00+00:00'
[2024-05-29T00:48:54.470+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T00:48:54.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T00:48:54.473+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/etl/extract.py", line 7, in extrair_dados
    data_interval_end_plus_7 = data_interval_end.add(days=7).strftime("%Y-%m-%d")
                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'add'
[2024-05-29T00:48:54.492+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=extrair_dados, run_id=scheduled__2024-05-21T07:15:00+00:00, execution_date=20240521T071500, start_date=20240529T004853, end_date=20240529T004854
[2024-05-29T00:48:54.519+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1977 for task extrair_dados ('str' object has no attribute 'add'; 5982)
[2024-05-29T00:48:54.578+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T00:48:54.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
