[2024-05-29T00:44:43.010+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T00:44:43.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-20T11:25:00+00:00 [queued]>
[2024-05-29T00:44:43.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-20T11:25:00+00:00 [queued]>
[2024-05-29T00:44:43.048+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T00:44:43.065+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair_dados> on 2024-05-20 11:25:00+00:00
[2024-05-29T00:44:43.073+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4446) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T00:44:43.075+0000] {standard_task_runner.py:63} INFO - Started process 4453 to run task
[2024-05-29T00:44:43.075+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'extrair_dados', 'scheduled__2024-05-20T11:25:00+00:00', '--job-id', '1487', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpz5mkglvg']
[2024-05-29T00:44:43.077+0000] {standard_task_runner.py:91} INFO - Job 1487: Subtask extrair_dados
[2024-05-29T00:44:43.131+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.extrair_dados scheduled__2024-05-20T11:25:00+00:00 [running]> on host 0473b835f7f4
[2024-05-29T00:44:43.243+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='extrair_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T11:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T11:25:00+00:00'
[2024-05-29T00:44:43.246+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T00:44:43.247+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T00:44:43.248+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/etl/extract.py", line 7, in extrair_dados
    data_interval_end_plus_7 = data_interval_end.add(days=7).strftime("%Y-%m-%d")
                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'add'
[2024-05-29T00:44:43.260+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=extrair_dados, run_id=scheduled__2024-05-20T11:25:00+00:00, execution_date=20240520T112500, start_date=20240529T004443, end_date=20240529T004443
[2024-05-29T00:44:43.277+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1487 for task extrair_dados ('str' object has no attribute 'add'; 4453)
[2024-05-29T00:44:43.296+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T00:44:43.308+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
