[2024-05-25T19:05:47.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:05:47.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T04:45:00+00:00 [queued]>
[2024-05-25T19:05:47.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T04:45:00+00:00 [queued]>
[2024-05-25T19:05:47.636+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:05:47.651+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 04:45:00+00:00
[2024-05-25T19:05:47.662+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:05:47.664+0000] {standard_task_runner.py:63} INFO - Started process 367 to run task
[2024-05-25T19:05:47.664+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T04:45:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpfenhwxev']
[2024-05-25T19:05:47.666+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask criar_pasta
[2024-05-25T19:05:47.724+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T04:45:00+00:00 [running]> on host 0473b835f7f4
[2024-05-25T19:05:47.854+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T04:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T04:45:00+00:00'
[2024-05-25T19:05:47.857+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:05:47.858+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:05:47.859+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-25T19:05:47.872+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T04:45:00+00:00, execution_date=20240517T044500, start_date=20240525T190547, end_date=20240525T190547
[2024-05-25T19:05:47.886+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 92 for task criar_pasta (name 'Path' is not defined; 367)
[2024-05-25T19:05:47.931+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:05:47.943+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:42:22.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:42:22.416+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T04:45:00+00:00 [queued]>
[2024-05-29T01:42:22.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T04:45:00+00:00 [queued]>
[2024-05-29T01:42:22.475+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:42:22.563+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 04:45:00+00:00
[2024-05-29T01:42:22.584+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:42:22.587+0000] {standard_task_runner.py:63} INFO - Started process 181 to run task
[2024-05-29T01:42:22.592+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T04:45:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpsod_ts_e']
[2024-05-29T01:42:22.599+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask criar_pasta
[2024-05-29T01:42:22.767+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T04:45:00+00:00 [running]> on host 6665b0710315
[2024-05-29T01:42:23.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T04:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T04:45:00+00:00'
[2024-05-29T01:42:23.019+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:42:23.031+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:42:23.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:42:23.078+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T04:45:00+00:00, execution_date=20240517T044500, start_date=20240529T014222, end_date=20240529T014223
[2024-05-29T01:42:23.187+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:42:23.299+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:42:23.328+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
