[2024-05-25T19:05:16.733+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:05:16.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:05:00+00:00 [queued]>
[2024-05-25T19:05:16.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:05:00+00:00 [queued]>
[2024-05-25T19:05:16.766+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:05:16.777+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 01:05:00+00:00
[2024-05-25T19:05:16.784+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:05:16.786+0000] {standard_task_runner.py:63} INFO - Started process 218 to run task
[2024-05-25T19:05:16.786+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T01:05:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpdp01nl0i']
[2024-05-25T19:05:16.787+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask criar_pasta
[2024-05-25T19:05:16.830+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:05:00+00:00 [running]> on host 0473b835f7f4
[2024-05-25T19:05:16.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T01:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T01:05:00+00:00'
[2024-05-25T19:05:16.930+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:05:16.932+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:05:16.933+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-25T19:05:16.944+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T01:05:00+00:00, execution_date=20240517T010500, start_date=20240525T190516, end_date=20240525T190516
[2024-05-25T19:05:16.958+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task criar_pasta (name 'Path' is not defined; 218)
[2024-05-25T19:05:17.007+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:05:17.030+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:05:17.035+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:35:45.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:35:45.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:05:00+00:00 [queued]>
[2024-05-29T01:35:45.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:05:00+00:00 [queued]>
[2024-05-29T01:35:45.296+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:35:45.350+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 01:05:00+00:00
[2024-05-29T01:35:45.367+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:35:45.371+0000] {standard_task_runner.py:63} INFO - Started process 343 to run task
[2024-05-29T01:35:45.374+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T01:05:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmp3m4t4k2f']
[2024-05-29T01:35:45.378+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask criar_pasta
[2024-05-29T01:35:45.518+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:05:00+00:00 [running]> on host dd333ca35f8c
[2024-05-29T01:35:45.808+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T01:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T01:05:00+00:00'
[2024-05-29T01:35:45.812+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:35:45.815+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:35:45.817+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:35:45.843+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T01:05:00+00:00, execution_date=20240517T010500, start_date=20240529T013545, end_date=20240529T013545
[2024-05-29T01:35:45.927+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:35:45.959+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
